name: Deploy to Firebase Hosting and Functions on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16' # Justert til en sannsynligvis støttet versjon
      - run: npm install -g firebase-tools
      - run: cd functions && npm install
      - run: firebase deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPACE_50ED0 }}'
          channelId: live
          projectId: space-50ed0
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}